# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

# Overwrite or add rules to create your own house style
#
# # Use `[a, [b, c]]` not `[ a, [ b, c ] ]`
# Layout/SpaceInsideArrayLiteralBrackets:
#   Enabled: false

plugins:
  - rubocop-performance
  - rubocop-rails

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.4

Layout/IndentationWidth:
  Enabled: true
  Width: 2

Layout/EndAlignment:
  Enabled: true

Layout/FirstParameterIndentation:
  Enabled: true

Style/StringLiterals:
  EnforcedStyle: single_quotes
